// Generated by scripts/import-synonym-library.py from local synonym source files.
// Do not edit this file by hand when refreshing the imported synonym set.

export const synonymLibrary = [
  {
    "id": "syn-001",
    "rank": 1,
    "headword": "resemble",
    "partOfSpeech": "v.",
    "meaningZh": "像，与......相似",
    "substitutions": [
      "like",
      "look",
      "be similar to"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-002",
    "rank": 2,
    "headword": "recognize",
    "partOfSpeech": "v.",
    "meaningZh": "认出，识别；承 认",
    "substitutions": [
      "perceive",
      "acknowledge",
      "realize",
      "appreciate",
      "admit",
      "identify",
      "comprehend",
      "understand",
      "know"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-003",
    "rank": 3,
    "headword": "adjust",
    "partOfSpeech": "v.",
    "meaningZh": "调整，使适合",
    "substitutions": [
      "change",
      "modify",
      "shift",
      "alter"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-004",
    "rank": 4,
    "headword": "approach",
    "partOfSpeech": "n.",
    "meaningZh": "方法",
    "substitutions": [
      "method"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-005",
    "rank": 5,
    "headword": "fundamental",
    "partOfSpeech": "adj.",
    "meaningZh": "基本的，基础 的",
    "substitutions": [
      "rudimentary",
      "preliminary",
      "basic"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-006",
    "rank": 6,
    "headword": "rely on",
    "partOfSpeech": "",
    "meaningZh": "依靠，依赖",
    "substitutions": [
      "depend on"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-007",
    "rank": 7,
    "headword": "domestic",
    "partOfSpeech": "adj.",
    "meaningZh": "家庭的；国内 的",
    "substitutions": [
      "home",
      "local",
      "national"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-008",
    "rank": 8,
    "headword": "measure",
    "partOfSpeech": "v.",
    "meaningZh": "测量",
    "substitutions": [
      "calculate",
      "assess",
      "evaluate"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-009",
    "rank": 9,
    "headword": "trait",
    "partOfSpeech": "n.",
    "meaningZh": "特性，特征",
    "substitutions": [
      "characteristic",
      "feature",
      "property"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-010",
    "rank": 10,
    "headword": "coin",
    "partOfSpeech": "v.",
    "meaningZh": "创造",
    "substitutions": [
      "first used",
      "invent"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-011",
    "rank": 11,
    "headword": "artificial",
    "partOfSpeech": "adj.",
    "meaningZh": "人造的，仿造 的",
    "substitutions": [
      "synthetic",
      "man-made"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-012",
    "rank": 12,
    "headword": "prompt",
    "partOfSpeech": "v.",
    "meaningZh": "促进，激起",
    "substitutions": [
      "initiate",
      "immediately"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-013",
    "rank": 13,
    "headword": "exchange",
    "partOfSpeech": "v.",
    "meaningZh": "交换",
    "substitutions": [
      "share",
      "apply A to B"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-014",
    "rank": 14,
    "headword": "underlie",
    "partOfSpeech": "v.",
    "meaningZh": "成为......基础",
    "substitutions": [
      "based on",
      "ground",
      "root"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-015",
    "rank": 15,
    "headword": "ignore",
    "partOfSpeech": "v.",
    "meaningZh": "忽视，不顾",
    "substitutions": [
      "neglect",
      "overlook",
      "underestimate"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-016",
    "rank": 16,
    "headword": "fertiliser",
    "partOfSpeech": "n.",
    "meaningZh": "化肥，肥料",
    "substitutions": [
      "chemical",
      "toxic",
      "unnatural"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-017",
    "rank": 17,
    "headword": "diversity",
    "partOfSpeech": "n.",
    "meaningZh": "多样性，差异",
    "substitutions": [
      "variety",
      "difference"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-018",
    "rank": 18,
    "headword": "detect",
    "partOfSpeech": "v.",
    "meaningZh": "查明，发现",
    "substitutions": [
      "find",
      "look for",
      "seek",
      "search"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-019",
    "rank": 19,
    "headword": "isolate",
    "partOfSpeech": "v.",
    "meaningZh": "使隔离，使孤立",
    "substitutions": [
      "inaccessible"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-020",
    "rank": 20,
    "headword": "avoid",
    "partOfSpeech": "v.",
    "meaningZh": "避免",
    "substitutions": [
      "escape",
      "evitable"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-021",
    "rank": 21,
    "headword": "budget",
    "partOfSpeech": "n.",
    "meaningZh": "预算",
    "substitutions": [
      "fund",
      "financial"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-022",
    "rank": 22,
    "headword": "adapt to",
    "partOfSpeech": "",
    "meaningZh": "使适应",
    "substitutions": [
      "suit"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-023",
    "rank": 23,
    "headword": "alternative",
    "partOfSpeech": "adj.",
    "meaningZh": "供替代的，供 选择的 n.替代品",
    "substitutions": [
      "substitute"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-024",
    "rank": 24,
    "headword": "compensate",
    "partOfSpeech": "n.",
    "meaningZh": "补偿，赔偿",
    "substitutions": [
      "make up",
      "offset"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-025",
    "rank": 25,
    "headword": "component",
    "partOfSpeech": "n.",
    "meaningZh": "成分，要素",
    "substitutions": [
      "proportion"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-026",
    "rank": 26,
    "headword": "military",
    "partOfSpeech": "adj.",
    "meaningZh": "军事的",
    "substitutions": [
      "weapon",
      "army"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-027",
    "rank": 27,
    "headword": "criteria",
    "partOfSpeech": "n.",
    "meaningZh": "标准",
    "substitutions": [
      "standard"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-028",
    "rank": 28,
    "headword": "curriculum",
    "partOfSpeech": "n.",
    "meaningZh": "课程",
    "substitutions": [
      "syllabus",
      "course of study"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-029",
    "rank": 29,
    "headword": "feasible",
    "partOfSpeech": "adj.",
    "meaningZh": "可行的",
    "substitutions": [
      "realistic",
      "viable"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-030",
    "rank": 30,
    "headword": "constrain",
    "partOfSpeech": "v.",
    "meaningZh": "束缚，限制",
    "substitutions": [
      "stop",
      "control"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-031",
    "rank": 31,
    "headword": "deficiency",
    "partOfSpeech": "n.",
    "meaningZh": "缺陷，缺点",
    "substitutions": [
      "shortage",
      "defect",
      "weakness"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-032",
    "rank": 32,
    "headword": "supplement",
    "partOfSpeech": "v.",
    "meaningZh": "补充",
    "substitutions": [
      "provision"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-033",
    "rank": 33,
    "headword": "distinguish",
    "partOfSpeech": "v.",
    "meaningZh": "区别，辨别",
    "substitutions": [
      "separate",
      "differentiate"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-034",
    "rank": 34,
    "headword": "analyze",
    "partOfSpeech": "v.",
    "meaningZh": "分析，解释",
    "substitutions": [
      "examine",
      "diagnose"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-035",
    "rank": 35,
    "headword": "emphasize",
    "partOfSpeech": "v.",
    "meaningZh": "强调，着重",
    "substitutions": [
      "focus on",
      "stress"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-036",
    "rank": 36,
    "headword": "enormous",
    "partOfSpeech": "adj.",
    "meaningZh": "庞大的 巨大的 ，",
    "substitutions": [
      "massive",
      "large"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-037",
    "rank": 37,
    "headword": "imitate",
    "partOfSpeech": "v.",
    "meaningZh": "模仿",
    "substitutions": [
      "mimic",
      "copy"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-038",
    "rank": 38,
    "headword": "impair",
    "partOfSpeech": "v.",
    "meaningZh": "削弱，减少",
    "substitutions": [
      "damage",
      "diminish",
      "decrease"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-039",
    "rank": 39,
    "headword": "hinder",
    "partOfSpeech": "v.",
    "meaningZh": "阻碍",
    "substitutions": [
      "impede",
      "prevent",
      "deter",
      "obstacle"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-040",
    "rank": 40,
    "headword": "legitimate",
    "partOfSpeech": "adj.",
    "meaningZh": "合法的",
    "substitutions": [
      "legal"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-041",
    "rank": 41,
    "headword": "limitation",
    "partOfSpeech": "n.",
    "meaningZh": "限制",
    "substitutions": [
      "restriction"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-042",
    "rank": 42,
    "headword": "convention",
    "partOfSpeech": "n.",
    "meaningZh": "手法；习俗",
    "substitutions": [
      "tradition"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-043",
    "rank": 43,
    "headword": "demanding",
    "partOfSpeech": "adj.",
    "meaningZh": "苛求的",
    "substitutions": [
      "troublesome"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-044",
    "rank": 44,
    "headword": "determine",
    "partOfSpeech": "v.",
    "meaningZh": "决定",
    "substitutions": [
      "decide"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-045",
    "rank": 45,
    "headword": "accelerate",
    "partOfSpeech": "v.",
    "meaningZh": "加速，促进；强调",
    "substitutions": [
      "speed up"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-046",
    "rank": 46,
    "headword": "ancient",
    "partOfSpeech": "adj.",
    "meaningZh": "古代的;古老的",
    "substitutions": [
      "aged"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-047",
    "rank": 47,
    "headword": "beneficial",
    "partOfSpeech": "adj.",
    "meaningZh": "有益的",
    "substitutions": [
      "advantageous",
      "wholesome"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-048",
    "rank": 48,
    "headword": "chronic",
    "partOfSpeech": "adj.",
    "meaningZh": "慢性的，长期 性的",
    "substitutions": [
      "lasting"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-049",
    "rank": 49,
    "headword": "conscious",
    "partOfSpeech": "adj.",
    "meaningZh": "有意识的，神 志清醒的",
    "substitutions": [
      "aware",
      "knowing"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-050",
    "rank": 50,
    "headword": "minimize",
    "partOfSpeech": "v.",
    "meaningZh": "最小化，使...... 减少到最少",
    "substitutions": [
      "reduce",
      "lessen"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-051",
    "rank": 51,
    "headword": "immunity",
    "partOfSpeech": "n.",
    "meaningZh": "免疫力",
    "substitutions": [
      "resistance"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-052",
    "rank": 52,
    "headword": "Imperative",
    "partOfSpeech": "adj.",
    "meaningZh": "必要的，紧急 的",
    "substitutions": [
      "compelling",
      "necessary",
      "urgent"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-053",
    "rank": 53,
    "headword": "secrete",
    "partOfSpeech": "v.",
    "meaningZh": "分泌",
    "substitutions": [
      "discharge",
      "exude"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-054",
    "rank": 54,
    "headword": "exaggerate",
    "partOfSpeech": "v.",
    "meaningZh": "夸大，夸张",
    "substitutions": [
      "overstate"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-055",
    "rank": 55,
    "headword": "transmit",
    "partOfSpeech": "v.",
    "meaningZh": "传达，传输",
    "substitutions": [
      "pass",
      "send",
      "transfer"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-056",
    "rank": 56,
    "headword": "extinct",
    "partOfSpeech": "v.",
    "meaningZh": "灭绝",
    "substitutions": [
      "die out",
      "lost"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-057",
    "rank": 57,
    "headword": "guarantee",
    "partOfSpeech": "v.",
    "meaningZh": "保证，担保",
    "substitutions": [
      "assure"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-058",
    "rank": 58,
    "headword": "inherit",
    "partOfSpeech": "v.",
    "meaningZh": "继承",
    "substitutions": [
      "receive"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-059",
    "rank": 59,
    "headword": "witness",
    "partOfSpeech": "n.",
    "meaningZh": "见证，证据；目 击者",
    "substitutions": [
      "view"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-060",
    "rank": 60,
    "headword": "magnetic",
    "partOfSpeech": "adj.",
    "meaningZh": "有磁性的",
    "substitutions": [
      "attractive"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-061",
    "rank": 61,
    "headword": "loss",
    "partOfSpeech": "n.",
    "meaningZh": "减少；亏损；失 败；遗失的",
    "substitutions": [
      "waste",
      "gone"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-062",
    "rank": 62,
    "headword": "option",
    "partOfSpeech": "n.",
    "meaningZh": "选择",
    "substitutions": [
      "choice"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-063",
    "rank": 63,
    "headword": "prefer to",
    "partOfSpeech": "",
    "meaningZh": "更喜欢",
    "substitutions": [
      "rather"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-064",
    "rank": 64,
    "headword": "priority",
    "partOfSpeech": "n.",
    "meaningZh": "优先权",
    "substitutions": [
      "preference",
      "preferential"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-065",
    "rank": 65,
    "headword": "primary",
    "partOfSpeech": "adj.",
    "meaningZh": "主要的",
    "substitutions": [
      "principle",
      "main"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-066",
    "rank": 66,
    "headword": "potential",
    "partOfSpeech": "n.",
    "meaningZh": "潜能 adj.潜在的",
    "substitutions": [
      "possibility"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-067",
    "rank": 67,
    "headword": "quantity",
    "partOfSpeech": "n.",
    "meaningZh": "量，数量",
    "substitutions": [
      "number"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-068",
    "rank": 68,
    "headword": "settle",
    "partOfSpeech": "v.",
    "meaningZh": "解决；定居，稳定",
    "substitutions": [
      "figure out"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-069",
    "rank": 69,
    "headword": "sophisticate",
    "partOfSpeech": "v.",
    "meaningZh": "使复杂",
    "substitutions": [
      "complicate"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-070",
    "rank": 70,
    "headword": "specific",
    "partOfSpeech": "adj.",
    "meaningZh": "明确的；特殊的",
    "substitutions": [
      "detailed",
      "particular"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-071",
    "rank": 71,
    "headword": "survive",
    "partOfSpeech": "v.",
    "meaningZh": "存活，幸存",
    "substitutions": [
      "remain"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-072",
    "rank": 72,
    "headword": "swift",
    "partOfSpeech": "adj.",
    "meaningZh": "迅速的，敏捷 的，立刻的",
    "substitutions": [
      "quick",
      "rapid"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-073",
    "rank": 73,
    "headword": "unexpectedly",
    "partOfSpeech": "adv.",
    "meaningZh": "出乎意料的",
    "substitutions": [
      "surprising"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-074",
    "rank": 74,
    "headword": "surrounding",
    "partOfSpeech": "n.",
    "meaningZh": "环境",
    "substitutions": [
      "setting",
      "environment"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-075",
    "rank": 75,
    "headword": "attempt",
    "partOfSpeech": "n.",
    "meaningZh": "试图，尝试",
    "substitutions": [
      "test"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-076",
    "rank": 76,
    "headword": "expertise",
    "partOfSpeech": "n.",
    "meaningZh": "专门技术",
    "substitutions": [
      "knowledge",
      "skill"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-077",
    "rank": 77,
    "headword": "faculty",
    "partOfSpeech": "n.",
    "meaningZh": "能力，才能；全 体教员",
    "substitutions": [
      "ability"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-078",
    "rank": 78,
    "headword": "donate",
    "partOfSpeech": "v.",
    "meaningZh": "捐赠",
    "substitutions": [
      "contribute"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-079",
    "rank": 79,
    "headword": "dynamics",
    "partOfSpeech": "n.",
    "meaningZh": "动力学",
    "substitutions": [
      "energy",
      "force",
      "move"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-080",
    "rank": 80,
    "headword": "incentive",
    "partOfSpeech": "n.",
    "meaningZh": "刺激,鼓励;动机",
    "substitutions": [
      "motive",
      "stimulus"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-081",
    "rank": 81,
    "headword": "mortality",
    "partOfSpeech": "n.",
    "meaningZh": "死亡率",
    "substitutions": [
      "death"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-082",
    "rank": 82,
    "headword": "peripheral",
    "partOfSpeech": "adj.",
    "meaningZh": "外围的，次要 的",
    "substitutions": [
      "unimportant",
      "minor"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-083",
    "rank": 83,
    "headword": "vicinity",
    "partOfSpeech": "n.",
    "meaningZh": "邻近，附近",
    "substitutions": [
      "neighbourhood",
      "nearby"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-084",
    "rank": 84,
    "headword": "threaten",
    "partOfSpeech": "v.",
    "meaningZh": "威胁，危及",
    "substitutions": [
      "endanger",
      "jeopardize",
      "risk",
      "hazard"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-085",
    "rank": 85,
    "headword": "practice",
    "partOfSpeech": "n.",
    "meaningZh": "实行；练习",
    "substitutions": [
      "exercise"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-086",
    "rank": 86,
    "headword": "bacteria",
    "partOfSpeech": "n.",
    "meaningZh": "细菌",
    "substitutions": [
      "virus",
      "germ",
      "microbe"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-087",
    "rank": 87,
    "headword": "be subject to",
    "partOfSpeech": "",
    "meaningZh": "受......支配",
    "substitutions": [
      "face"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-088",
    "rank": 88,
    "headword": "innate",
    "partOfSpeech": "adj.",
    "meaningZh": "天生的；内在 的，直觉的",
    "substitutions": [
      "built-in",
      "inborn"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-089",
    "rank": 89,
    "headword": "pattern",
    "partOfSpeech": "n.",
    "meaningZh": "模式",
    "substitutions": [
      "formation"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-090",
    "rank": 90,
    "headword": "therapy",
    "partOfSpeech": "n.",
    "meaningZh": "治疗，理疗",
    "substitutions": [
      "treatment"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-091",
    "rank": 91,
    "headword": "original",
    "partOfSpeech": "adj.",
    "meaningZh": "原始的,最初的",
    "substitutions": [
      "initial",
      "fist"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-092",
    "rank": 92,
    "headword": "confidential",
    "partOfSpeech": "adj.",
    "meaningZh": "机密的,秘密的",
    "substitutions": [
      "undisclosed",
      "secret",
      "hidden"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-093",
    "rank": 93,
    "headword": "cognitive",
    "partOfSpeech": "adj.",
    "meaningZh": "认知的",
    "substitutions": [
      "mental"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-094",
    "rank": 94,
    "headword": "comply with",
    "partOfSpeech": "",
    "meaningZh": "照做，遵守",
    "substitutions": [
      "obey"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-095",
    "rank": 95,
    "headword": "consult",
    "partOfSpeech": "v.",
    "meaningZh": "查阅,商量,请教, 咨询",
    "substitutions": [
      "ask for advice"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-096",
    "rank": 96,
    "headword": "superior",
    "partOfSpeech": "adj.",
    "meaningZh": ".上级的;优秀 的",
    "substitutions": [
      "higher",
      "upper"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-097",
    "rank": 97,
    "headword": "co-operation",
    "partOfSpeech": "n.",
    "meaningZh": "合作，协作",
    "substitutions": [
      "support",
      "work together"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-098",
    "rank": 98,
    "headword": "co-ordinate",
    "partOfSpeech": "v.",
    "meaningZh": "使......协调",
    "substitutions": [
      "organize",
      "harmonize"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-099",
    "rank": 99,
    "headword": "differ",
    "partOfSpeech": "v.",
    "meaningZh": "使......相异； 使......不同",
    "substitutions": [
      "vary"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-100",
    "rank": 100,
    "headword": "signal",
    "partOfSpeech": "n.",
    "meaningZh": "信号",
    "substitutions": [
      "symbol",
      "mark",
      "sign"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-101",
    "rank": 101,
    "headword": "abandon",
    "partOfSpeech": "v.",
    "meaningZh": "放弃，遗弃",
    "substitutions": [
      "quit",
      "give up",
      "forsake",
      "derelict"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-102",
    "rank": 102,
    "headword": "fragile",
    "partOfSpeech": "adj.",
    "meaningZh": "脆弱的",
    "substitutions": [
      "vulnerable"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-103",
    "rank": 103,
    "headword": "retain",
    "partOfSpeech": "v.",
    "meaningZh": "记住",
    "substitutions": [
      "maintain"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-104",
    "rank": 104,
    "headword": "vanish",
    "partOfSpeech": "n.",
    "meaningZh": "消失，绝迹",
    "substitutions": [
      "disappear"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-105",
    "rank": 105,
    "headword": "erode",
    "partOfSpeech": "v.",
    "meaningZh": "侵蚀",
    "substitutions": [
      "rust"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-106",
    "rank": 106,
    "headword": "induce",
    "partOfSpeech": "v.",
    "meaningZh": "引起，引诱",
    "substitutions": [
      "cause",
      "lead to"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-107",
    "rank": 107,
    "headword": "stable",
    "partOfSpeech": "adj.",
    "meaningZh": "稳定的",
    "substitutions": [
      "constant",
      "unchanged"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-108",
    "rank": 108,
    "headword": "integrate",
    "partOfSpeech": "v.",
    "meaningZh": "使......成整体",
    "substitutions": [
      "combine",
      "whole"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-109",
    "rank": 109,
    "headword": "equal",
    "partOfSpeech": "adj.",
    "meaningZh": "平等的;相等 的；胜任的",
    "substitutions": [
      "fair"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-110",
    "rank": 110,
    "headword": "grant",
    "partOfSpeech": "v.",
    "meaningZh": "拨款；授予",
    "substitutions": [
      "offer"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-111",
    "rank": 111,
    "headword": "solve",
    "partOfSpeech": "",
    "meaningZh": "解决",
    "substitutions": [
      "deal with",
      "cope with",
      "handle",
      "resolve",
      "address",
      "tackle"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-112",
    "rank": 112,
    "headword": "hurt",
    "partOfSpeech": "",
    "meaningZh": "损害",
    "substitutions": [
      "injure",
      "harm",
      "undermine"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-113",
    "rank": 113,
    "headword": "render",
    "partOfSpeech": "",
    "meaningZh": "给与",
    "substitutions": [
      "impart",
      "provide",
      "supply",
      "afford"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-114",
    "rank": 114,
    "headword": "develop",
    "partOfSpeech": "",
    "meaningZh": "培养",
    "substitutions": [
      "cultivate",
      "foster"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-115",
    "rank": 115,
    "headword": "advantage",
    "partOfSpeech": "",
    "meaningZh": "优势",
    "substitutions": [
      "merit",
      "virtue",
      "benefit",
      "upside",
      "strength"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-116",
    "rank": 116,
    "headword": "disadvantage",
    "partOfSpeech": "",
    "meaningZh": "缺陷",
    "substitutions": [
      "demerit",
      "drawback",
      "downside"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-117",
    "rank": 117,
    "headword": "puzzle",
    "partOfSpeech": "",
    "meaningZh": "使迷惑",
    "substitutions": [
      "bewilder",
      "perplex",
      "baffle"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-118",
    "rank": 118,
    "headword": "crucial",
    "partOfSpeech": "",
    "meaningZh": "重 要 的",
    "substitutions": [
      "critical",
      "important",
      "significant",
      "vital",
      "substantial",
      "indispensable"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-119",
    "rank": 119,
    "headword": "believe",
    "partOfSpeech": "",
    "meaningZh": "认 为",
    "substitutions": [
      "insist",
      "assert",
      "conclude",
      "deem",
      "argue",
      "be convinced",
      "be firmly convinced",
      "be fully convinced"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-120",
    "rank": 120,
    "headword": "protect",
    "partOfSpeech": "",
    "meaningZh": "保护",
    "substitutions": [
      "conserve",
      "preserve"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-121",
    "rank": 121,
    "headword": "ensure",
    "partOfSpeech": "",
    "meaningZh": "确保",
    "substitutions": [
      "pledge"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-122",
    "rank": 122,
    "headword": "baneful",
    "partOfSpeech": "",
    "meaningZh": "有害的",
    "substitutions": [
      "evil",
      "harmful",
      "detrimental"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-123",
    "rank": 123,
    "headword": "request",
    "partOfSpeech": "",
    "meaningZh": "要求",
    "substitutions": [
      "demand",
      "needs",
      "requisition"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-124",
    "rank": 124,
    "headword": "eliminate",
    "partOfSpeech": "",
    "meaningZh": "消除",
    "substitutions": [
      "clear",
      "remove",
      "clear up",
      "take away",
      "smooth away"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-125",
    "rank": 125,
    "headword": "bring about",
    "partOfSpeech": "",
    "meaningZh": "导致",
    "substitutions": [
      "result in",
      "spark off",
      "conduce to",
      "procure",
      "generate"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-126",
    "rank": 126,
    "headword": "therefore",
    "partOfSpeech": "",
    "meaningZh": "因此",
    "substitutions": [
      "thus",
      "hence",
      "consequently",
      "as a consequence",
      "accordingly",
      "as a result of this"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-127",
    "rank": 127,
    "headword": "grow to",
    "partOfSpeech": "",
    "meaningZh": "增长至",
    "substitutions": [
      "rise to",
      "increase to",
      "go up to",
      "climb to",
      "ascend to",
      "jump to",
      "shoot to"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-128",
    "rank": 128,
    "headword": "dip to",
    "partOfSpeech": "",
    "meaningZh": "降低至",
    "substitutions": [
      "fall to",
      "decline to",
      "decrease to",
      "drop to",
      "go down to",
      "reduce to",
      "slump to",
      "descend to",
      "sink to",
      "slide to"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-129",
    "rank": 129,
    "headword": "level out",
    "partOfSpeech": "",
    "meaningZh": "保 持 稳 定",
    "substitutions": [
      "do not change",
      "remain stable",
      "remain still",
      "remain steady",
      "be stable",
      "maintain the same level",
      "remain unchanged",
      "be still",
      "remain the same level",
      "stay constant",
      "keep at the same level",
      "level off",
      "stabilize",
      "keep its stability",
      "even out"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-130",
    "rank": 130,
    "headword": "dramatically",
    "partOfSpeech": "",
    "meaningZh": "急剧地",
    "substitutions": [
      "drastically",
      "sharply",
      "hugely",
      "enormously",
      "steeply",
      "substantially",
      "considerably",
      "significantly",
      "markedly",
      "surprisingly",
      "strikingly",
      "radically",
      "remarkably",
      "vastly",
      "noticeably"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-131",
    "rank": 131,
    "headword": "steadily",
    "partOfSpeech": "",
    "meaningZh": "平 稳 地",
    "substitutions": [
      "smoothly",
      "slightly",
      "marginally",
      "gradually",
      "moderately",
      "mildly"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-132",
    "rank": 132,
    "headword": "allege",
    "partOfSpeech": "",
    "meaningZh": "宣称",
    "substitutions": [
      "declare",
      "claim"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-133",
    "rank": 133,
    "headword": "happen",
    "partOfSpeech": "",
    "meaningZh": "发生",
    "substitutions": [
      "occur",
      "take place"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-134",
    "rank": 134,
    "headword": "reason",
    "partOfSpeech": "",
    "meaningZh": "原因",
    "substitutions": [
      "factor"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-135",
    "rank": 135,
    "headword": "development",
    "partOfSpeech": "",
    "meaningZh": "发展",
    "substitutions": [
      "advance",
      "progress"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-136",
    "rank": 136,
    "headword": "useful",
    "partOfSpeech": "",
    "meaningZh": "有益的",
    "substitutions": [
      "profitable",
      "rewarding"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-137",
    "rank": 137,
    "headword": "influence",
    "partOfSpeech": "",
    "meaningZh": "影响",
    "substitutions": [
      "impact"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-138",
    "rank": 138,
    "headword": "obvious",
    "partOfSpeech": "",
    "meaningZh": "明显的",
    "substitutions": [
      "evident",
      "self-evident",
      "manifest",
      "apparent",
      "crystal-clear"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-139",
    "rank": 139,
    "headword": "comprise",
    "partOfSpeech": "",
    "meaningZh": "占",
    "substitutions": [
      "take up",
      "account for",
      "constitute",
      "consist of",
      "occupy",
      "compose"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-140",
    "rank": 140,
    "headword": "compared with",
    "partOfSpeech": "",
    "meaningZh": "与...相比",
    "substitutions": [
      "compared to",
      "in comparison with",
      "in comparison to",
      "by comparison with",
      "by comparison to"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-141",
    "rank": 141,
    "headword": "by contrast",
    "partOfSpeech": "",
    "meaningZh": "对 比 而 言",
    "substitutions": [
      "in contrast",
      "on the other hand",
      "on the contrary",
      "conversely"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-142",
    "rank": 142,
    "headword": "show",
    "partOfSpeech": "",
    "meaningZh": "展示",
    "substitutions": [
      "reveal",
      "illustrate",
      "demonstrate",
      "depict",
      "present",
      "represent",
      "describe"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-143",
    "rank": 143,
    "headword": "fluctuate",
    "partOfSpeech": "",
    "meaningZh": "波 动",
    "substitutions": [
      "go ups and downs",
      "display a fluctuation",
      "demonstrate a fluctuation"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-144",
    "rank": 144,
    "headword": "practically",
    "partOfSpeech": "",
    "meaningZh": "事 实 上",
    "substitutions": [
      "in practice",
      "essentially",
      "in essence",
      "in reality",
      "in effect",
      "in fact",
      "as a matter of fact",
      "it is a fact that"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-145",
    "rank": 145,
    "headword": "namely",
    "partOfSpeech": "",
    "meaningZh": "换言 之",
    "substitutions": [
      "that is to say",
      "in other words",
      "to put it like this",
      "to put it differently",
      "to put it from another way",
      "to put it from another angle"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-146",
    "rank": 146,
    "headword": "individuals",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "characters",
      "folks"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-147",
    "rank": 147,
    "headword": "positive",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "favorable",
      "perfect",
      "pleasurable",
      "excellent",
      "outstanding"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-148",
    "rank": 148,
    "headword": "a slice of",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "quite a few"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-149",
    "rank": 149,
    "headword": "affair",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "business",
      "matter"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-150",
    "rank": 150,
    "headword": "get many benefits",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "reap huge fruits"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-151",
    "rank": 151,
    "headword": "in my opinion",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "for my part",
      "from my own perspective"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-152",
    "rank": 152,
    "headword": "shopper",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "client",
      "consumer",
      "purchaser"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-153",
    "rank": 153,
    "headword": "exceedingly",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "extremely",
      "intensely"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-154",
    "rank": 154,
    "headword": "unnecessary",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "avoidable",
      "hardly necessary",
      "hardly inevitable"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-155",
    "rank": 155,
    "headword": "sb take interest in",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "sb. be interested in",
      "sth appeals to sb",
      "sth exerts a tremendous fascination on sb"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-156",
    "rank": 156,
    "headword": "attract one's attention",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "capture one's attention"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-157",
    "rank": 157,
    "headword": "aspect",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "facet",
      "dimension",
      "sphere"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-158",
    "rank": 158,
    "headword": "indicate",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "suggest",
      "fear",
      "be indicative of",
      "be suggestive of",
      "be fearful of"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-159",
    "rank": 159,
    "headword": "give rise to",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "trigger"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-160",
    "rank": 160,
    "headword": "pay attention to",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "pour attention into"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-161",
    "rank": 161,
    "headword": "remember",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "bear in mind that"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-162",
    "rank": 162,
    "headword": "be against",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "disagree with sth",
      "frown on sth"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-163",
    "rank": 163,
    "headword": "for example",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "for instance",
      "to name only a few",
      "as an example"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-164",
    "rank": 164,
    "headword": "almost impossible",
    "partOfSpeech": "",
    "meaningZh": "",
    "substitutions": [
      "next to",
      "virtually impossible"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-165",
    "rank": 165,
    "headword": "poor",
    "partOfSpeech": "",
    "meaningZh": "贫穷的",
    "substitutions": [
      "needy",
      "impoverished",
      "poverty-stricken"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-166",
    "rank": 166,
    "headword": "rich",
    "partOfSpeech": "",
    "meaningZh": "富裕的",
    "substitutions": [
      "wealthy",
      "affluent",
      "well-to-do",
      "well-off"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-167",
    "rank": 167,
    "headword": "healthy",
    "partOfSpeech": "",
    "meaningZh": "健康的",
    "substitutions": [
      "robust",
      "sound"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-168",
    "rank": 168,
    "headword": "amazing",
    "partOfSpeech": "",
    "meaningZh": "惊人的",
    "substitutions": [
      "extraordinary",
      "miraculous"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-169",
    "rank": 169,
    "headword": "beautiful",
    "partOfSpeech": "",
    "meaningZh": "美丽的",
    "substitutions": [
      "gorgeous",
      "eye-catching"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-170",
    "rank": 170,
    "headword": "energetic",
    "partOfSpeech": "",
    "meaningZh": "有活力的",
    "substitutions": [
      "dynamic",
      "vigorous",
      "animated"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-171",
    "rank": 171,
    "headword": "popular",
    "partOfSpeech": "",
    "meaningZh": "流行的",
    "substitutions": [
      "prevailing",
      "prevalent",
      "pervasive"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-172",
    "rank": 172,
    "headword": "improve",
    "partOfSpeech": "",
    "meaningZh": "提高，加强",
    "substitutions": [
      "enhance",
      "promote",
      "strengthen",
      "optimize"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-173",
    "rank": 173,
    "headword": "destroy",
    "partOfSpeech": "",
    "meaningZh": "拆除",
    "substitutions": [
      "tear down",
      "knock down",
      "eradicate"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-174",
    "rank": 174,
    "headword": "encourage",
    "partOfSpeech": "",
    "meaningZh": "激发，鼓励",
    "substitutions": [
      "motivate",
      "stimulate",
      "spur"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-175",
    "rank": 175,
    "headword": "complete",
    "partOfSpeech": "",
    "meaningZh": "完成",
    "substitutions": [
      "fulfill",
      "accomplish",
      "achieve"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-176",
    "rank": 176,
    "headword": "ease",
    "partOfSpeech": "",
    "meaningZh": "减轻",
    "substitutions": [
      "alleviate",
      "relieve",
      "lighten"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-177",
    "rank": 177,
    "headword": "dangerous",
    "partOfSpeech": "",
    "meaningZh": "危险",
    "substitutions": [
      "perils",
      "hazardous"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-178",
    "rank": 178,
    "headword": "pollution",
    "partOfSpeech": "",
    "meaningZh": "污染",
    "substitutions": [
      "contamination"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-179",
    "rank": 179,
    "headword": "human beings",
    "partOfSpeech": "",
    "meaningZh": "人类",
    "substitutions": [
      "mankind",
      "human race"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-180",
    "rank": 180,
    "headword": "old people",
    "partOfSpeech": "",
    "meaningZh": "老人",
    "substitutions": [
      "the old",
      "the elderly",
      "the aged",
      "senior citizens"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-181",
    "rank": 181,
    "headword": "happiness",
    "partOfSpeech": "",
    "meaningZh": "幸福",
    "substitutions": [
      "cheerfulness",
      "well-being"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-182",
    "rank": 182,
    "headword": "teachers",
    "partOfSpeech": "",
    "meaningZh": "老师",
    "substitutions": [
      "instructors",
      "educators",
      "lecturers",
      "tutors"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-183",
    "rank": 183,
    "headword": "education",
    "partOfSpeech": "",
    "meaningZh": "教育",
    "substitutions": [
      "schooling",
      "family parenting",
      "upbringing"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-184",
    "rank": 184,
    "headword": "young people",
    "partOfSpeech": "",
    "meaningZh": "青少年",
    "substitutions": [
      "youngsters",
      "youths",
      "adolescents"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-185",
    "rank": 185,
    "headword": "merits",
    "partOfSpeech": "",
    "meaningZh": "优点",
    "substitutions": [
      "superiority"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-186",
    "rank": 186,
    "headword": "responsibility",
    "partOfSpeech": "",
    "meaningZh": "责任",
    "substitutions": [
      "obligation",
      "duty",
      "liability"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-187",
    "rank": 187,
    "headword": "capacity",
    "partOfSpeech": "",
    "meaningZh": "能力",
    "substitutions": [
      "power",
      "career",
      "employment",
      "profession"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-188",
    "rank": 188,
    "headword": "enjoyment",
    "partOfSpeech": "",
    "meaningZh": "娱乐",
    "substitutions": [
      "pastimes",
      "recreation",
      "entertainment"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-189",
    "rank": 189,
    "headword": "children",
    "partOfSpeech": "",
    "meaningZh": "孩子",
    "substitutions": [
      "offspring",
      "descendant"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-190",
    "rank": 190,
    "headword": "be filled with",
    "partOfSpeech": "",
    "meaningZh": "充满了",
    "substitutions": [
      "be awash with",
      "be inundate with",
      "be saturated with"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-191",
    "rank": 191,
    "headword": "struggle for",
    "partOfSpeech": "",
    "meaningZh": "努力",
    "substitutions": [
      "aspire after",
      "strive for",
      "spare no efforts for"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-192",
    "rank": 192,
    "headword": "embark on",
    "partOfSpeech": "",
    "meaningZh": "从事",
    "substitutions": [
      "set about",
      "go in for"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-193",
    "rank": 193,
    "headword": "in contemporary society",
    "partOfSpeech": "",
    "meaningZh": "在当代",
    "substitutions": [
      "in present-day society",
      "in this day and age"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  },
  {
    "id": "syn-194",
    "rank": 194,
    "headword": "a host of",
    "partOfSpeech": "",
    "meaningZh": "大量的",
    "substitutions": [
      "a multitude of",
      "a vast number of",
      "a vast amount of"
    ],
    "difficulty": "exam-synonym",
    "tags": [
      "exam-synonym"
    ]
  }
];
